### PR TITLE
Revert changes to force proto objects to be NSObject subclasses

### PR DESCRIPTION
**Pull request by dpassage**
An upcoming PR for NavdyClient removes the need to force protobuf messages to be subclasses of NSObject.

After this, the only differences between our branch and the protobuf-swift master are the ones to allow Xcode 8 to compile the project using Swift 2.3. This will go away entirely when we move to Swift 3.

@bwill please to OK.

### CODE REVIEW

**Comment by bwill** [comment]
+1

**Comment by j2tobias** [comment]
@bwill - I think you forgot to remove my username to all Navdy's repo. I am seeing some commits after logging in my GitHub.

**Comment by bwill** [comment]
@j2tobias which repos?  Maybe they're public repos?

**Comment by j2tobias** [comment]
@bwill - this protobuf-swift, libevent... are this public?

**Comment by bwill** [comment]
@j2tobias - yes - checkout out https://github.com/watching  there are probably public navdy repos in there.

**Comment by j2tobias** [comment]
okay. thanks.

**Pull request merged**
